// <auto-generated />
using HedgePair.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HedgePair.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522092210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HedgePair.API.Models.FinancialInstrument", b =>
                {
                    b.Property<int>("FinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FIN_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinId"));

                    b.Property<string>("DealNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Deal_Number");

                    b.Property<string>("DealStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("deal_status");

                    b.Property<string>("DealType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("deal_type");

                    b.Property<decimal>("NotionalAmt")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Notional_Amt");

                    b.HasKey("FinId");

                    b.HasIndex("DealNumber")
                        .IsUnique();

                    b.ToTable("Financial_Instrument", (string)null);

                    b.HasData(
                        new
                        {
                            FinId = 1,
                            DealNumber = "DL1234567",
                            DealStatus = "Active",
                            DealType = "BOND",
                            NotionalAmt = 100000.50m
                        },
                        new
                        {
                            FinId = 2,
                            DealNumber = "DL2345678",
                            DealStatus = "Active",
                            DealType = "BOND",
                            NotionalAmt = 200000.75m
                        },
                        new
                        {
                            FinId = 3,
                            DealNumber = "DL3456789",
                            DealStatus = "Active",
                            DealType = "BOND",
                            NotionalAmt = 150000.00m
                        },
                        new
                        {
                            FinId = 4,
                            DealNumber = "DL4567890",
                            DealStatus = "Active",
                            DealType = "BOND",
                            NotionalAmt = 250000.25m
                        },
                        new
                        {
                            FinId = 5,
                            DealNumber = "DL5678901",
                            DealStatus = "Inactive",
                            DealType = "BOND",
                            NotionalAmt = 300000.10m
                        },
                        new
                        {
                            FinId = 6,
                            DealNumber = "DL1234568",
                            DealStatus = "Active",
                            DealType = "SWAP",
                            NotionalAmt = 100000.50m
                        },
                        new
                        {
                            FinId = 7,
                            DealNumber = "DL2345679",
                            DealStatus = "Active",
                            DealType = "SWAP",
                            NotionalAmt = 200000.75m
                        },
                        new
                        {
                            FinId = 8,
                            DealNumber = "DL3456780",
                            DealStatus = "Active",
                            DealType = "SWAP",
                            NotionalAmt = 150000.00m
                        },
                        new
                        {
                            FinId = 9,
                            DealNumber = "DL4567810",
                            DealStatus = "Active",
                            DealType = "SWAP",
                            NotionalAmt = 250000.25m
                        },
                        new
                        {
                            FinId = 10,
                            DealNumber = "DL5678911",
                            DealStatus = "Inactive",
                            DealType = "SWAP",
                            NotionalAmt = 300000.10m
                        });
                });

            modelBuilder.Entity("HedgePair.API.Models.HedgePair", b =>
                {
                    b.Property<int>("HedgePairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HEDGE_PAIR_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HedgePairId"));

                    b.Property<int>("BondFinId")
                        .HasColumnType("int")
                        .HasColumnName("BOND_FIN_ID");

                    b.Property<decimal>("BondNotionalAmt")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BOND_NOTIONAL_AMT");

                    b.Property<int>("SwapFinId")
                        .HasColumnType("int")
                        .HasColumnName("SWAP_FIN_ID");

                    b.Property<decimal>("SwapNotionalAmt")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SWAP_NOTIONAL_AMT");

                    b.HasKey("HedgePairId");

                    b.HasIndex("BondFinId")
                        .IsUnique();

                    b.HasIndex("SwapFinId")
                        .IsUnique();

                    b.ToTable("Hedge_Pair", (string)null);
                });

            modelBuilder.Entity("HedgePair.API.Models.HedgePair", b =>
                {
                    b.HasOne("HedgePair.API.Models.FinancialInstrument", "Bond")
                        .WithOne("BondPair")
                        .HasForeignKey("HedgePair.API.Models.HedgePair", "BondFinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HedgePair.API.Models.FinancialInstrument", "Swap")
                        .WithOne("SwapPair")
                        .HasForeignKey("HedgePair.API.Models.HedgePair", "SwapFinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bond");

                    b.Navigation("Swap");
                });

            modelBuilder.Entity("HedgePair.API.Models.FinancialInstrument", b =>
                {
                    b.Navigation("BondPair");

                    b.Navigation("SwapPair");
                });
#pragma warning restore 612, 618
        }
    }
}
